## Tensorflow Basic Syntax Tutorial

In [1]:
# Import Tensorflow
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
# Defining Contants in TF
hello = tf.constant("Hello")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
type(world)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
# Run the Operation inside the session
# "with": Use it as it automatically opens the session and closes it at the end. So no need to specifically close the session.
with tf.Session() as sess:
    # Run the block of Code
    result = sess.run(hello+world)

In [9]:
print(result)

b'HelloWorld'


In [10]:
# Addition Example
a = tf.constant(20)

In [11]:
b = tf.constant(12)

In [12]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [13]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

TF Keeps track of how many times we execute a task as add_1:0 , add_2:0 etc.

In [15]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [16]:
result

32

In [17]:
# Other Operations
const = tf.constant(15)

In [18]:
# Filled Matrix. ex. 3 x 3 matrix filled with value 12
fill_mat = tf.fill((3,3),12)

In [19]:
# Tensor with all Zeros
# ex. 4x4 matrix of zeros
zero = tf.zeros((4,4))

In [20]:
# Tensor with all Ones
# ex. 2x2 matrix of 1's
one = tf.ones((2,2))

In [21]:
# Random Normal Distribution
# Returns random values from a normal distribution
# Inputs: shape, mean, stddev, seed, name.
randn = tf.random_normal((4,4), mean=0, stddev=0.1)

In [22]:
# Uniform Distribution
# Inputs: shape, minval, maxval, seed, name
randu = tf.random_uniform((4,4), minval=0, maxval=2)

In [24]:
# Put all operations into a List
my_ops = [const, fill_mat, zero, one, randn, randu]

In [25]:
# New: TF Interactive Session
# Use: Only in Jupyter Notebook Env.
# All lines after this are considered to be in the 
# with tf.Session() 
sess = tf.InteractiveSession()

In [27]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

15


[[12 12 12]
 [12 12 12]
 [12 12 12]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.]
 [ 1.  1.]]


[[-0.0775511   0.11218798  0.03848493  0.11288817]
 [ 0.05894494  0.12976669  0.05997078 -0.0033202 ]
 [ 0.08409756 -0.14795618 -0.02202632 -0.04746122]
 [-0.02984547  0.0530672   0.0172161  -0.1404337 ]]


[[ 1.0375855   0.859231    0.55579352  1.35501957]
 [ 0.32095528  0.31377792  0.2011838   1.8564086 ]
 [ 1.00330091  0.21983743  0.86492729  1.69011784]
 [ 0.59191251  0.06098223  0.05971265  0.23603487]]




In [28]:
# Most of the functions come with eval method
for op in my_ops:
    print(op.eval())
    print('\n')

15


[[12 12 12]
 [12 12 12]
 [12 12 12]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.]
 [ 1.  1.]]


[[-0.10188838 -0.07311358  0.02677389  0.08535703]
 [ 0.00017167 -0.07173368  0.00721841  0.13237208]
 [-0.16978933 -0.05295559 -0.01339333  0.04860229]
 [-0.05393058 -0.04635439  0.07645427  0.13012134]]


[[ 0.1653955   0.37792563  0.74540186  0.67041564]
 [ 0.22719002  1.07751131  1.11767721  1.71406054]
 [ 1.85396171  1.5955174   0.55291033  1.4405849 ]
 [ 1.42411852  0.56398177  0.42427611  1.95797491]]




In [29]:
# Matrix Multiplication
a = tf.constant([[1,2],
                [3,4]])

In [31]:
# Shape of Matrix "a": 2 x 2
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [32]:
b = tf.constant([[10],
                 [100]])

In [33]:
# Shape of Matrix "b" : 2 x 1
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [34]:
# Result of Matrix Multiplication
result = tf.matmul(a,b)

In [36]:
# Evaluate the Matrix Multiplication
sess.run(result)

array([[210],
       [430]])